# Generated by Django 3.1.2 on 2020-10-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ciudad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='direccon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
