# Generated by Django 3.1.2 on 2020-10-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_mascota_especie'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='estado',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='tamaño',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
