# Generated by Django 3.1.2 on 2020-10-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0006_auto_20201012_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_mascota', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='vacuna',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='estado',
        ),
        migrations.DeleteModel(
            name='Vacuna',
        ),
        migrations.AddField(
            model_name='mascota',
            name='estado',
            field=models.ManyToManyField(to='mascota.Estado'),
        ),
    ]
