# Generated by Django 3.1.2 on 2020-10-12 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_auto_20201012_0116'),
        ('mascota', '0003_auto_20201011_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.persona'),
        ),
    ]
